apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mern
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 31000  # Optional: specify a port within the range 30000-32767
  selector:
    role: frontend

